### ISSUE TITLE
Windows 10

### ISSUE THREAD

**Issue by MeTaLiKiD** [LPardue/SpotifyStatusApplet#3]
Hi, the app works fine on my laptot (Windows 7 Ultimate x64) but not on my tower (Windows 10).

Do you have any idea if the applet works on Windows 10 ?

Does the applet write logs to see if an error occured ?

Thanks

**Comment by arjankuijpers** [comment]
This App works on Windows 10 (version 1.2 beta 1

**Comment by JeffreyO** [comment]
You must install the normal Spotify desktop program for it to work. It doesn't appear to work with the Windows Store (UWP) application. This appears to be due to SpotifyWebHelper.exe either not being present or runnable.
