### ISSUE TITLE
Disables Playback Hotkeys When Running

### ISSUE THREAD

**Issue by mjmoore** [LPardue/SpotifyStatusApplet#6]
Spotify running, launch the applet. Can no longer use play/pause keyboard keys and instead must the Spotify interface.

**Comment by LPardue** [comment]
My media key no longer work at all after upgrading to Windows 10. 

We have recently landed a change to add skip and play/pause functionality to the soft 2-4 keys.

**Comment by JeffreyO** [comment]
I've found in Windows 7 that the track skip keys don't work when explorer.exe has focus. Though this is an issue with the OS. The same happens when I use my keyboard media keys.

**Comment by mjmoore** [comment]
I'm going to close this. No movement on the issue and I no longer use this applet.
